title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://spicyfishandchips.github.io/fft-mods/

aux_links:
  Template Repository: https://spicyfishandchips.github.io/fft-mods/

color_scheme: light